[package]
name = "risc-v-rust-bare-metal"
version = "0.1.0"
edition = "2021"

[dependencies]
buddy_system_allocator = "0.11.0"
panic-halt = "1.0.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
